CREATE TABLE if not exists subscriptions_type
(
    subscriptions_type_id INT            NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(180)   NOT NULL,
    access_months         INT,
    price                 NUMERIC(10, 2) NOT NULL,
    product_key           VARCHAR(180)
);

CREATE TABLE if not exists user_type
(
    user_type_id INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(180) NOT NULL,
    description  VARCHAR(255) NOT NULL
);

CREATE TABLE if not exists users
(
    users_id              INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(180) NOT NULL,
    email                 VARCHAR(150) NOT NULL,
    phone                 VARCHAR(50)  NOT NULL,
    cpf                   VARCHAR(25)  NOT NULL,
    dt_subscription       TIMESTAMP    NOT NULL,
    dt_expiration         TIMESTAMP    NOT NULL,
    user_type_id          INT,
    subscriptions_type_id INT
);

CREATE TABLE if not exists user_payment_info
(
    user_payment_info_id INT            NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number          VARCHAR(25)    NOT NULL,
    card_expiration      TIMESTAMP      NOT NULL,
    card_security_code   VARCHAR(4)     NOT NULL,
    price                NUMERIC(10, 2) NOT NULL,
    instalments          INT            NOT NULL,
    dt_payment           TIMESTAMP      NOT NULL,
    user_id              INT
);

ALTER TABLE
    users
    ADD CONSTRAINT users_email_unique UNIQUE (email);
ALTER TABLE
    users
    ADD CONSTRAINT users_cpf_unique UNIQUE (cpf);
ALTER TABLE
    users
    ADD CONSTRAINT users_phone_unique UNIQUE (phone);

ALTER TABLE
    users
    ADD CONSTRAINT fk_user_type_id FOREIGN KEY (user_type_id) REFERENCES user_type (user_type_id);
ALTER TABLE
    users
    ADD CONSTRAINT fk_subscriptions_type_id FOREIGN KEY (subscriptions_type_id) REFERENCES subscriptions_type (subscriptions_type_id);

ALTER TABLE
    subscriptions_type
    ADD CONSTRAINT subscriptions_type_product_key_unique UNIQUE (product_key);

ALTER TABLE
    user_payment_info
    ADD CONSTRAINT user_payment_info_card_number_unique UNIQUE (card_number);

ALTER TABLE
    user_payment_info
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (users_id);

INSERT INTO subscriptions_type (name, access_months, price, product_key)
VALUES ('PLANO MENSAL', 1, 75.00, 'MONTH22');
INSERT INTO subscriptions_type (name, access_months, price, product_key)
VALUES ('PLANO ANUAL', 12, 697.00, 'YEAR22');
INSERT INTO subscriptions_type (name, access_months, price, product_key)
VALUES ('PLANO VITALICIO', NULL, 1497.00, 'PERPETUAL22');

INSERT INTO user_type (name, description)
VALUES ('PROFESSOR', 'Professores da plataforma - cadastro administrativo');
INSERT INTO user_type (name, description)
VALUES ('ADMINISTRADOR', 'Administrado da plataforma - cadastro administrativo');
INSERT INTO user_type (name, description)
VALUES ('ALUNO', 'Aluno da plataforma - cadastro via fluxo normal');